services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket-mgmt-postgres
    environment:
      POSTGRES_USER: ticket_admin
      POSTGRES_PASSWORD: NgxLAu1PoCKEi9dmxkg3XxV
      POSTGRES_DB: ticket_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
